name: update_latest

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  update_latest:
    runs-on: ubuntu-latest

    steps:
      - name: "‚¨áÔ∏è Checkout"
        uses: actions/checkout@v4
        with:
          ref: "main"
          token: "${{ secrets.REPO_DATA_TOKEN }}"

      - name: "üêç Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: "üêç Install dependencies"
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install build

      - name: "‚öôÔ∏è Run update_latest"
        run: |
          export PYTHONPATH="$PYTHONPATH:./src"

          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          python workflows/update_latest.py

      - name: "‚¨ÜÔ∏è Push"
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "ü§ñ [update_latest.yml] $(date '+%Y-%m-%d-%H%M')"
          git pull origin main --rebase
          git push origin main
